name: Feature Request
description: Suggest an idea for endpoint.nvim
title: "[Feature] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: framework
    attributes:
      label: Which framework would this apply to?
      description: Select all that apply
      multiple: true
      options:
        - Spring Boot (Java)
        - NestJS (TypeScript) 
        - Express (JavaScript/TypeScript)
        - All frameworks
        - Framework agnostic
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe your use case and how this feature would help you
      placeholder: |
        I would use this feature to...
        This would help me when...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request here
    validations:
      required: false